#!/bin/zsh
set -euo pipefail

ROOT="${0:A:h:h}"
source "$ROOT/scripts/lib/profile.sh"
require_profile_vars OPENCODE_INDEX_ROOTS OPENCODE_INDEX_AUTODISCOVER OPENCODE_DESKTOP_STATE OPENCODE_INDEX_DB LMSTUDIO_EMBEDDING_URL EMBED_ID

INDEXER="$ROOT/mcp/local_code_index.py"

export OPENCODE_INDEX_ROOTS="${OPENCODE_INDEX_ROOTS}"
export OPENCODE_INDEX_AUTODISCOVER="${OPENCODE_INDEX_AUTODISCOVER}"
export OPENCODE_DESKTOP_STATE="${OPENCODE_DESKTOP_STATE}"
export OPENCODE_INDEX_BACKGROUND=0
export OPENCODE_INDEX_DB="${OPENCODE_INDEX_DB}"
export LMSTUDIO_EMBEDDING_URL="${LMSTUDIO_EMBEDDING_URL}"
export LMSTUDIO_EMBEDDING_MODEL="${EMBED_ID}"

"$ROOT/scripts/ensure-lmstudio-models.sh"
/usr/bin/python3 "$INDEXER" --index
