# model.yaml is an open standard for defining cross-platform, composable AI models
# Learn more at https://modelyaml.org
model: unsloth/qwen3.6-27b
base:
  - key: unsloth/qwen3.6-27b-gguf
    sources:
      - type: huggingface
        user: unsloth
        repo: Qwen3.6-27B-GGUF
metadataOverrides:
  domain: llm
  architectures:
    - qwen35
  compatibilityTypes:
    - gguf
  paramsStrings:
    - 27B
  minMemoryUsageBytes: 32000000000
  contextLengths:
    - 262144
  vision: true
  reasoning: true
  trainedForToolUse: true
config:
  operation:
    fields:
      - key: llm.prediction.temperature
        value: 0.6
      - key: llm.prediction.topPSampling
        value:
          checked: true
          value: 0.95
      - key: llm.prediction.topKSampling
        value: 20
      - key: llm.prediction.minPSampling
        value:
          checked: true
          value: 0
customFields:
  - key: enableThinking
    displayName: Enable Thinking
    description: Controls whether the model will think before replying
    type: boolean
    defaultValue: false
    effects:
      - type: setJinjaVariable
        variable: enable_thinking
